# Never release this
# This is an intentionally fake "lxml" module
# generated by collective.recipe.mockedeggs recipe

from setuptools import setup

version = '3.4.0'

setup(
    name='lxml',
    version=version,
    description="Fake lxml",
    author="Ingeniweb",
    author_email='thomas.desvenain@gmail.com',
    url='http://pypi.python.org/pypi/collective.recipe.mockedeggs/',
    )

